apiVersion: v1
kind: ConfigMap
metadata:
  name: solr-config
  labels:
    app: solr
    chart: {{ template "portal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  JAVA_OPTIONS: {{ .Values.solr.javaOptions | default "-Xms512m -Xmx512m" | quote }}
  NSS_SDB_USE_CACHE: "no"
  SOLR_PORT: "8983"
