apiVersion: v1
kind: Secret
metadata:
  name: minio-secret  
  labels:
    app: minio    
type: Opaque
data:
  MINIO_ACCESS_KEY: MVJwOWhsajVEVQ==
  MINIO_SECRET_KEY: MDFEZU13UFplYlhXdFE1a0JKbkNEczNldnpaZ1d6SkZaclBtRGw2Yg==